version: '3'
 
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ozbambaz
      MYSQL_DATABASE: app_db
      MYSQL_USER: ozbambaz
      MYSQL_DATABASE: app_db
    ports:
      - "6033:3306"
    volumes:
      - ./setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: